### ISSUE TITLE
콤보수, 타격타임 등 가시성 문제

### ISSUE THREAD

**Issue by jaemin-im** [Gengaozo/UBMS#1]
* 콤보수, 타격타임(SLOW/FAST +-~~ms) 등이 노트와 같은 흰색으로 구성되어 있어 가시성에 있어서 문제를 느꼈습니다.

**Comment by Unengine** [comment]
콤보/타이밍 텍스트에 Outline Shader 적용 완료했습니다. Outline 크기가 부족하신가요?

**Comment by jaemin-im** [comment]
충분한 것 같습니다. close하겠습니다.
